//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Coffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin1
    {
        public int IDAdmin { get; set; }
        public string HoTenAdmin { get; set; }
        public string SDTAdmin { get; set; }
        public string DiaChiAdmin { get; set; }
        public string GmailAdmin { get; set; }
        public int IDNguoiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
