//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Coffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chu
    {
        public string SDTChu { get; set; }
        public int IDChu { get; set; }
        public string HoTenChu { get; set; }
        public string DiaChiChu { get; set; }
        public string GmailChu { get; set; }
        public int IDNguoiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
