    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace Web_Coffee.Models
    {
        using System;
        using System.Collections.Generic;
    
        public partial class NguoiDung
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
            public NguoiDung()
            {
                this.Admin1 = new HashSet<Admin1>();
                this.KhachHang = new HashSet<KhachHang>();
                this.NhanVien = new HashSet<NhanVien>();
            }
    
            public int IDNguoiDung { get; set; }
            public string Role { get; set; }
            public string UserName { get; set; }
            public string Pass { get; set; }
    
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<Admin1> Admin1 { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<KhachHang> KhachHang { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<NhanVien> NhanVien { get; set; }
        }
    }
