//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Coffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int IDNhanVien { get; set; }
        public string HoTenNV { get; set; }
        public string DiaChiNV { get; set; }
        public string RoleNV { get; set; }
        public string GmaiNV { get; set; }
        public string SdtNV { get; set; }
        public int IDNguoiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
