//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Coffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
        }

        [Key]
        public int IDSanPham { get; set; }

        [Required(ErrorMessage = "Mã sản phẩm là bắt buộc")]
        [StringLength(50, ErrorMessage = "Mã sản phẩm không được vượt quá 50 ký tự")]
        public string CodeSanPham { get; set; }

        [Required(ErrorMessage = "Tên sản phẩm là bắt buộc")]
        [StringLength(100, ErrorMessage = "Tên sản phẩm không được vượt quá 100 ký tự")]
        public string TenSanPham { get; set; }

        [Required(ErrorMessage = "Giá sản phẩm là bắt buộc")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Giá sản phẩm phải lớn hơn 0")]
        public double Gia { get; set; }

        [StringLength(255, ErrorMessage = "Đường dẫn hình ảnh không được vượt quá 255 ký tự")]
        public string HinhAnh { get; set; }

        [Required(ErrorMessage = "Kích cỡ sản phẩm là bắt buộc")]
        [StringLength(10, ErrorMessage = "Kích cỡ sản phẩm không được vượt quá 10 ký tự")]
        public string Size { get; set; }

        [Required(ErrorMessage = "Số lượng sản phẩm là bắt buộc")]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng sản phẩm không được âm")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "ID Nhà Cung Cấp là bắt buộc")]
        public int IDNCC { get; set; }

        [Required(ErrorMessage = "ID Loại Sản Phẩm là bắt buộc")]
        public int IDCategory { get; set; }
        [NotMapped] // This attribute is used to ensure Entity Framework ignores this property in the database
        public HttpPostedFileBase ImageUpload { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
